### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by AynurKhasanov** [georgelviv/fb2Reader#1]
click to upload, but nothing happens. Help help please.

**Comment by georgelviv** [comment]
Some errors ? You make bower and npm install?

**Comment by AynurKhasanov** [comment]
No, I just copied a localhost and opened in the browser index.php.

**Comment by georgelviv** [comment]
Please install nodejs , and then run npm install on project folder in your command line

**Comment by AynurKhasanov** [comment]
installed nodejs , how to install npm on project?

**Comment by georgelviv** [comment]
Open command line on project folder and write npm install

**Comment by AynurKhasanov** [comment]
Thank you all set. And how to make a link to book?
Example in php "<a href="/frontend/web/index.php?r=admin%2Fbook%2Fview&amp;id=2" class="btn btn-primary" role="button">Read this book</a>"

**Comment by sensboston** [comment]
Could you please provide detailed, step by step instruction with the list of pre-requisites for Ubuntu? Thanks!

P.S. Have you ever thought to offer your rider to the Russian online libraries like flibusta or lib.rus.ec? These guys really need a good fb2 online reader, I think so.

**Comment by georgelviv** [comment]
Thank for your interest to current reporistory. Current project is web application ,which works with nodejs server. So it does not matter which OS do you use, just install node js, and you will be able to run project.
About idea, to offer reader for some web sites, I guess it good and interesting idea, but this project was developed with teaching purpose,  so if some popular online libraries want to extend theirs main functionality with online reader , I always happy to accept offers)

**Comment by sensboston** [comment]
Hmm, it's definitely not enough. I installed node js to my Rpi (Raspberry Pi with Apache server installed), copied **dist** folder to the web root but nothing happened. I can see a default page (index.html) but your reader doesn't work. What's why I asked for "step by step for dummies" instruction!

As for online libraries, there is no "offer", of course! (and I'm not the owner of these libraries). But (I believe so!) you may want to bring your project to the hundreds thousands customers, don't you (instead of 4 stars on github)?

But it's too early (from my side) to discuss this topic; I've never seen your reader at work... By the way, could you provide a link to working reader at the start page?

P.S. We can probably switch to Russian (but not Ukrainian - I know Ukrainian but can't speak/type freely) and to email, instead of public forums/issue reports?

**Comment by microtoom** [comment]
Does not open other books, except the built-in Alice.

**Comment by microtoom** [comment]
Does not open other books, except the built-in Alice. Animation hangs at 100%.
and in line it is.

`C:\Users\microtoom\fb2Reader-master\node_modules\jquery-file-upload-middleware\lib\uploadhandler.js:76
                    async.each(files, _.bind(function(fileInfo, cb) {
                          ^

TypeError: async.each is not a function
    at UploadHandler.<anonymous> (C:\Users\microtoom\fb2Reader-master\node_modules\jquery-file-upload-middleware\lib\uploadhandler.js:76:27)
    at wrapper (C:\Users\microtoom\fb2Reader-master\node_modules\lodash\lodash.js:4935:19)
    at C:\Users\microtoom\fb2Reader-master\node_modules\jquery-file-upload-middleware\lib\uploadhandler.js:143:37
    at FSReqWrap.oncomplete (fs.js:141:20)`
